namespace:
  name: prod
 
image:
  repository: nginx 
  tag: 1.17.0

replicaCount: 1

service:
  port: 80
  type: ClusterIP
  
resources:
  requests:
    cpu: 70m
    memory: 128Mi
    
configmap:
  data: "version: 1.17.0"


