namespace:
  name: demo
 
image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  port: 8111
  type: ClusterIP
  
resources:
  requests:
    cpu: 50m
    memory: 256Mi

configmap:
  data: "version: alpine"


